version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - mimmi20
  assignees:
  - mimmi20
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: browscap/browscap-php
    versions:
    - ">= 0"
  - dependency-name: laminas/laminas-hydrator
    versions:
    - ">= 0"
  - dependency-name: monolog/monolog
    versions:
    - ">= 0"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 0"
  - dependency-name: symfony/twig-bridge
    versions:
    - ">= 0"
  commit-message:
    prefix: Build
    include: scope
