language: php
sudo: false

php:
  - 7.1
  - 7.2

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $TRAVIS_BUILD_DIR/resources
    - $HOME/.composer/cache

stages:
  - composer validate
  - static code analysis
  - test
  - test with coverage

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv $COMPOSER_FLAGS

script: vendor/bin/phpunit -c phpunit.xml.dist --colors --no-coverage

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: vendor/bin/phpunit -c phpunit.xml.dist --colors --coverage-text --coverage-clover=clover.xml
      after_success:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar && php -n php-coveralls.phar --verbose --coverage_clover=clover.xml
        - bash <(curl -s https://codecov.io/bash) -f clover.xml -F phpunit

    - stage: composer validate
      php: 7.1
      env: COMPOSER_FLAGS=""
      install: skip
      script: composer validate

    - stage: static code analysis
      php: 7.1
      env:
        - TEST=phpcs
        - COMPOSER_FLAGS=""
      script: vendor/bin/phpcs --colors

    - stage: static code analysis
      php: 7.1
      env:
        - TEST=php-cs-fixer
        - COMPOSER_FLAGS=""
      script: vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.1
      env:
        - TEST=phpstan
        - COMPOSER_FLAGS=""
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src test
